<?php

header('Access-Control-Allow-Origin: *');

//////////////////////////////////////////////////////////
// Basic Auth
$AUTH_USER = 'digibot';
$AUTH_PASS = 'akl23kl!1l2kj9od13lkjsd';
header('Cache-Control: no-cache, must-revalidate, max-age=0');
$has_supplied_credentials = !(empty($_SERVER['PHP_AUTH_USER']) && empty($_SERVER['PHP_AUTH_PW']));
$is_not_authenticated = (
	!$has_supplied_credentials ||
	$_SERVER['PHP_AUTH_USER'] != $AUTH_USER ||
	$_SERVER['PHP_AUTH_PW']   != $AUTH_PASS
);
if ($is_not_authenticated) {
	header('HTTP/1.1 401 Authorization Required');
	header('WWW-Authenticate: Basic realm="Access denied"');
	exit;
}
//////////////////////////////////////////////////////////


$json = json_decode(file_get_contents("php://input"));
//file_put_contents('./log.txt', $json->id . "\n", FILE_APPEND);

$id = $json->id;
$sessionId = $json->sessionId;
$intent = $json->result->metadata->intentName;
$entity = $json->result->parameters->topic;
$entity1 = $json->result->parameters->subtopic;
$entity2 = $json->result->parameters->details;
$query = str_replace("'", "''",$json->result->resolvedQuery);
$orderUrl = 'https://digiretail.azurewebsites.net/action.ashx?action=json';
$jsonData = array(
    'command' => 'webhook_get_answer',
    'hook_id' => "$id"
);

//Encode the array into JSON.
$postData = json_encode($jsonData);
//echo $postData;


////////////////////////////////////////////////////////////
// send User Input to chatbase
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://chatbase-area120.appspot.com/api/message");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"api_key\": \"5ea1b233-3492-4c05-9514-39ec506e1286\",\"type\": \"user\",\"platform\": \"our-curl-test-platform\",\"message\": \"$query\",\"intent\": \"$intent\",\"version\": \"1.0\",\"user_id\": \"user$sessionId\"}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Cache-Control: no-cache";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
//    echo 'Error:';
} else {
//	echo $result;
}
curl_close ($ch);
////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////
// send our statement directly to database
$serverName = "digicentral.database.windows.net";   
$uid = "digicentral";
$pwd = "mupay1828!";    
$databaseName = "digicentral";   
$connectionInfo = array( "UID"=>$uid,                              
                         "PWD"=>$pwd,                              
                         "Database"=>$databaseName,
					     "CharacterSet" => "UTF-8");
/* Connect using SQL Server Authentication. */    

$conn = sqlsrv_connect( $serverName, $connectionInfo);        

if ($conn){
	/* Execute the query. */    
	$tsql = "webhook_get_answer '$sessionId','$query','$id','$intent','$entity','$entity1','$entity2'";

	$stmt = sqlsrv_query( $conn, $tsql);

	if( $stmt === false )  
	{  
		 echo "Error in statement preparation/execution.\n";  
		 die( print_r( sqlsrv_errors(), true));  
	}  

	while ($response = sqlsrv_fetch_array($stmt)) {
		echo $response[0];
		
		//////////////////////////////////////////////////////////
		// send RESPONSE to Chatbase
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		//	$ch = curl_init();
		//
		//	curl_setopt($ch, CURLOPT_URL, "https://chatbase-area120.appspot.com/api/message");
		//	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		//	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"api_key\": \"1dd09daf-03dd-4138-9a9f-6e353d240b6e\",\"type\": \"agent\",\"platform\": \"our-curl-test-platform\",\"message\": \"response\",\"version\": \"1.0\",\"user_id\": \"user$sessionId\"}");
		//	curl_setopt($ch, CURLOPT_POST, 1);
		//
		//	$headers = array();
		//	$headers[] = "Cache-Control: no-cache";
		//	$headers[] = "Content-Type: application/x-www-form-urlencoded";
		//	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		//
		//	$result = curl_exec($ch);
		//	if (curl_errno($ch)) {
		////		echo 'Error:' . curl_error($ch);
		//	}
		//	curl_close ($ch);	
		//////////////////////////////////////////////////////////
	}

	sqlsrv_free_stmt( $stmt);    
}else{
//	exit;
}
sqlsrv_close($conn);
//////////////////////////////////////////////////////////

	
	
